# Generated by Django 4.2.11 on 2024-06-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curd", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=200, unique=True)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
            options={"abstract": False,},
        ),
    ]
